### ISSUE TITLE
Conflict in `dmap` module name 

### ISSUE THREAD

**Issue by calops** [doums/dmap.nvim#2]
I have no idea if this is particular to my setup, but it seems like an actual issue.

The `dmap.lua` module conflicts with the `dmap/` module. When requiring it, it targets `dmap/init.lua` instead of `dmap.lua`, making it impossible to setup the plugin.

I feel like even if it is the package manager's fault ([lazy.nvim](https://github.com/folke/lazy.nvim)), it wouldn't hurt to name those files/directories something different just for clarity's sake. And as far as I can tell, it seems to be standard practice to have a `module/init.lua` file act as a single module?

**Comment by doums** [comment]
Hey, thx for reporting. You're probably right, related to how [lazy.nvim](https://github.com/folke/lazy.nvim) handles module loading? Anyway, I pushed a refactor bit that should fix the issue https://github.com/doums/dmap.nvim/commit/ac13e8e338afaeb11f592c142e9102496e89e514
